CREATE TABLE [dbo].[LINKS] (
    [ID]               UNIQUEIDENTIFIER NOT NULL,
    [CATALOGPRODUCTID] UNIQUEIDENTIFIER NOT NULL,
    [PRICERECORDINDEX] INT              NOT NULL,
    CONSTRAINT [LINKSPRIMARY] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [LINKSFOREIGNCATALOGPRODUCT] FOREIGN KEY ([CATALOGPRODUCTID]) REFERENCES [dbo].[PRODUCTS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [LINKSFOREIGNPRICERECORD] FOREIGN KEY ([PRICERECORDINDEX]) REFERENCES [dbo].[PRICESRECORDS] ([RECORDINDEX]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [LINKSUNIQUEID] UNIQUE NONCLUSTERED ([ID] ASC)
);

