CREATE TABLE [dbo].[PRICESRECORDS] (
    [RECORDINDEX] INT              IDENTITY (1, 1) NOT NULL,
    [PRICEID]     UNIQUEIDENTIFIER NOT NULL,
    [NAME]        NVARCHAR (1024)  NOT NULL,
    [STATE]       TINYINT          NOT NULL,
    [USED]        BIT              NOT NULL,
    [PRICE]       FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [DELETED]     BIT              DEFAULT ((0)) NOT NULL,
    [COMMENT]     NVARCHAR (1024)  DEFAULT ('') NOT NULL,
    [SKU]         NVARCHAR (50)    DEFAULT ('') NOT NULL,
    [STOCK]       INT              DEFAULT ((0)) NOT NULL,
    [INSTOCK]     INT              DEFAULT ((10000)) NOT NULL,
    CONSTRAINT [PRICESRECORDSPRIMARY] PRIMARY KEY CLUSTERED ([RECORDINDEX] ASC),
    CONSTRAINT [PRICESRECORDSFOREIGNPRICE] FOREIGN KEY ([PRICEID]) REFERENCES [dbo].[PRICES] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [PRICESRECORDSUNIQUEINDEX] UNIQUE NONCLUSTERED ([RECORDINDEX] ASC)
);

